var textures = [
	{name: 'cake_bottom', texture: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAV0lEQVR42mNgoAZYHqzwnxyMYsCOWPX/MBofRlaLYQC6IbjYeA3AZSM2cZK9gO4inC4gxiDaeAE9lEnyAjFRSJYXyI5GXF7Bm5BITZEEvUBSSqQoM1ECAHvFqyQXkgWpAAAAAElFTkSuQmCC'},
	{name: 'cake_side', texture: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAYUlEQVR42mNgGAWjAAoOHTr0//79+yRhkB4UA169fE0SxmoAiIa5hhAfwwAQXh6sAMbE8uEGTPeUgkuuj1CGs/HxQXpQDABJ7IhVB2MQmxAfwwCYJDIG2YRLDMMAcjBILwCrtTHpCEHg4gAAAABJRU5ErkJggg=='},
	{name: 'cake_top', texture: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAjklEQVR42q2T3QnAIAyEXcQx3H+KPPvanyFaIkTO9LQWKwTBcl+8Mw3hjyUiV875U6mmAvTg2M+5irHsqnkAkO474vcuYEupdvBdFYpnFFDEDoBCtMoBRMS8cwB09pYsk1cLfjdLFh5m1AeQEFlGwxtYDmw+hs+I72xl12Y25ybR5TAGsCHqVANY/plW1g14oK4NJ6IuzwAAAABJRU5ErkJggg=='}
]
